//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.Data
{
    using System;
    using System.Collections.Generic;
    
    public class tmodel
    {
        public int id { get; set; }
        public int year_id { get; set; }
        public int make_id { get; set; }
        public string model_na { get; set; }
        private List<string> _years = new List<string>();
        public virtual tmake tmake { get; set; }
        public virtual tyear tyear { get; set; }
        public List<string> Years { get => _years; set => _years = value; }

        public tmodel()
        {
            Years = GetYears();
        }

        private List<string> GetYears()
        {
            for (int i = DateTime.Now.Year; i >= 1925; --i)
            {
                _years.Add(i.ToString());
            }
            return _years;
        }

    }
}
