//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tservice
    {
        public int srvc_id { get; set; }
        public string srvc_na { get; set; }
        public System.DateTime crt_dt { get; set; }
    }
}
